### ISSUE TITLE
Provide usage examples

### ISSUE THREAD

**Issue by abshinn** [kwhanalytics/rdtools#10]
- Standardize degradation function outputs and printed output.
- Commit notebooks with usage examples of the code.
- Supply links to notebooks ([notebooks would be rendered so that users do not need to launch Jupyter Notebook to view the code and plots](http://blog.jupyter.org/2015/05/07/rendering-notebooks-on-github/)).

**Comment by mdeceglie** [comment]
This appears to be a duplicate of #13. I will close this and open a new issue on standardizing degradation function outputs.
