### ISSUE TITLE
Standardize degradation function outputs and printed output

### ISSUE THREAD

**Issue by mdeceglie** [kwhanalytics/rdtools#16]

**Comment by GregoryKimball** [comment]
For degradation function outputs, consider returning a tuple to separate the results from the processed data.  This would make it easier for the user to focus on standardized results.

For instance:
( [results dictionary] , [series or dataframe of YoY deltas])
( [results dictionary] , [series corresponding to the linear fit])

**Comment by mdeceglie** [comment]
Good suggestion, I'm working on an update to YOY at the moment and can include this.

**Comment by mdeceglie** [comment]
closed with the merge of pull request #22
