### ISSUE TITLE
Make OLS regression independent of time series frequency.

### ISSUE THREAD

**Issue by abshinn** [kwhanalytics/rdtools#4]
Right now, `rdtools.degradation_with_ols` assumes the input time series is monthly. This function should be generalized to handle other time series frequencies.

**Comment by mdeceglie** [comment]
I have addressed this for degradation_with_ols in the issue 4 branch. I suggest continued development on that branch to generalize the other rd methods before merging. Once merged into master, we can close this issue.

**Comment by mdeceglie** [comment]
Closed with merge from March 2.
