### ISSUE TITLE
Implement YOY degradation calc

### ISSUE THREAD

**Issue by abshinn** [kwhanalytics/rdtools#5]
@dirkjordan sent over a script with YOY in python. Take that code and implement it into the degradation module in rdtools.

**Comment by mdeceglie** [comment]
@abshinn - I can take this on if it is OK with you. Dirk has been working on tuning the various calculations on the data we have in house. I will have some time in early January to generalize them and integrate them into rdtools.

**Comment by abshinn** [comment]
Thanks, @mdeceglie. That is OK with me.

**Comment by mdeceglie** [comment]
Closed with merge from March 2.
